name: Setup go
description: "Setup go"
inputs:
  go_version:
    description: "go version"
    default: 1.18.0
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Go Env
      uses: actions/setup-go@v3
      with:
        go-version: ">=${{ inputs.go_version }}"

    - name: Print Go Version
      shell: bash
      run: go version
