name: "Setup databend binary"
description: "Setup databend binary"
inputs:
  tag:
    description: "databend build tag"
    required: true
runs:
  using: "composite"
  steps:
     
     - name: Install and run databend by binary with minio
       shell: bash
       run: |
         curl -LJO https://github.com/datafuselabs/databend/releases/download/${{ inputs.tag }}/databend-${{ inputs.tag }}-x86_64-unknown-linux-gnu.tar.gz
         tar zxvf databend-${{ inputs.tag }}-x86_64-unknown-linux-gnu.tar.gz

         docker run -d -p 9900:9000 --name minio \
         -e "MINIO_ACCESS_KEY=minioadmin" \
         -e "MINIO_SECRET_KEY=minioadmin" \
         -v /tmp/data:/data \
         -v /tmp/config:/root/.minio \
         minio/minio server /data

         export AWS_ACCESS_KEY_ID=minioadmin
         export AWS_SECRET_ACCESS_KEY=minioadmin
         export AWS_EC2_METADATA_DISABLED=true

         aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://testbucket

         export STORAGE_TYPE=s3
         export STORAGE_S3_BUCKET=testbucket
         export STORAGE_S3_ROOT=admin
         export STORAGE_S3_ENDPOINT_URL=http://127.0.0.1:9900
         export STORAGE_S3_ACCESS_KEY_ID=minioadmin
         export STORAGE_S3_SECRET_ACCESS_KEY=minioadmin
         export STORAGE_ALLOW_INSECURE=true      
         ./scripts/start.sh
