name: Setup python
description: "Setup python"
inputs:
  python_version:
    description: "python version"
    default: "3.10"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
  
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        architecture: 'x86'
