# ref https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Publish Docker image
description: "Check will do all essential checks"
inputs:
  docker_usename:
    description: "docker user name"
    required: true
  docker_password:
    description: "docker user name"
    required: true
  target:
    description: ""
    required: true
  platform:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_usename }}
        password: ${{ inputs.docker_password }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository
      
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platform }}
    
    - name: Image digest
      shell: bash
      run: echo ${{ steps.docker_build.outputs.digest }}