# ref https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Publish Docker image
description: "Check will do all essential checks"
inputs:
  docker_usename:
    description: "docker user name"
    required: true
  docker_password:
    description: "docker user password"
    required: true
  ecr_role_arn:
    description: "ECR Role ARN"
    required: true
  tags:
    description: ""
    required: true
  labels:
    description: ""
    required: true
  platform:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # login dockerhub 
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_usename }}
        password: ${{ inputs.docker_password }}

    # login ecr
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.ecr_role_arn }}
        role-duration-seconds: 900
        aws-region: us-east-2

    - name: Login to Public ECR
      shell: bash
      run: |
        docker login --username AWS --password $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws
      
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        platforms: ${{ inputs.platform }}

    - name: Image digest
      shell: bash
      run: echo ${{ steps.docker_build.outputs.digest }}