name: ci demo

# on: workflow_dispatch

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - '.github/workflows/ci_demo.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - '.github/workflows/ci_demo.yml'

jobs:
  build:
    name: Run demo ci 
    # if: github.repository == 'ZeaLoVe/action-player'
    runs-on: ubuntu-latest
    env:
      DEMO_ENV: demo
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: show info
        run: |
          pwd && ls -al && df -h && echo "${{ env.DEMO_ENV }}"

      - name: setup
        run: |
          make setup

      - name: build
        run: |
          make build
        
      - name: run
        run: |
          make run

      - if: ${{ failure() }}
        run: |
          echo "failed"