name: databend with s3(minio)

on: 
  workflow_dispatch:
    inputs:
      image_tags:
        description: "tags of databend image"
        required: false
        default: v0.7.115-nightly

jobs:
  run-logic-test:
    name: Run databen with s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Copy a file from s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # source: 's3://databend-benchmark-test/ontime_2006_100000.csv'
          source: 's3://databendcloud/tutorial/ontime_2006_100000.csv'
          dest: './ontime_2006_100000.csv'

      - name: Minio Setup for (ubuntu-latest only)
        shell: bash
        run: |
          docker run -d -p 9900:9000 --name minio \
                -e "MINIO_ACCESS_KEY=minioadmin" \
                -e "MINIO_SECRET_KEY=minioadmin" \
                minio/minio server /data

      - name: Copy test data
        run: |
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_EC2_METADATA_DISABLED=true
          aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://testbucket
          aws --endpoint-url http://127.0.0.1:9900/ s3 cp ontime_2006_100000.csv s3://testbucket/ontime_2006_100000.csv
          aws --endpoint-url http://127.0.0.1:9900/ s3 ls s3://testbucket

      - name: Install and run databend by binary
        run: |
          export STORAGE_TYPE=s3
          export STORAGE_S3_BUCKET=testbucket
          export STORAGE_S3_ROOT=admin
          export STORAGE_S3_ENDPOINT_URL=http://127.0.0.1:9900
          export STORAGE_S3_ACCESS_KEY_ID=minioadmin
          export STORAGE_S3_SECRET_ACCESS_KEY=minioadmin
          curl -LJO https://github.com/datafuselabs/databend/releases/download/${{ github.event.inputs.image_tags }}/databend-${{ github.event.inputs.image_tags }}-x86_64-unknown-linux-musl.tar.gz
          tar zxvf databend-${{ github.event.inputs.image_tags }}-x86_64-unknown-linux-musl.tar.gz
          ./scripts/start.sh

      - name: Install mysql client
        run: |
          sudo apt install mysql-client

      - name: Run test
        run: |
          cat sql/ontime.sql | mysql -h127.0.0.1 -uroot -P3307
          echo "COPY INTO ontime FROM 's3://testbucket/ontime_2006_100000.csv' credentials=(aws_key_id='minioadmin' aws_secret_key='minioadmin') FILE_FORMAT = ( type = 'CSV' field_delimiter = ',' record_delimiter = '\n' skip_header = 1 );" | mysql -h127.0.0.1 -uroot -P3307
          echo 'select count(*) from ontime;' | mysql -h127.0.0.1 -uroot -P3307
