name: databend logic test install by helm run on k3d

on: 
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      image_tags:
        description: "tags of databend image"
        required: false
        default: v0.7.80-nightly
      logic_test_images:
        description: "logic test image full name and tags"  
        required: true
        default: public.ecr.aws/i7g1w5q7/sqllogictest:latest
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - '.github/workflows/databend-logic-test.yml'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - '.github/workflows/databend-logic-test.yml'

jobs:
  run-logic-test:
    name: Run logic test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # usage: steps.databend_version.ouputs.VERSION
      - name: Get Databend version
        id: databend_version
        run: |
          LASTEST_TAG=$(curl -s GET https://api.github.com/repos/datafuselabs/databend/tags\?per_page\=1 | jq -r '.[].name')
          echo ::set-output name=VERSION::${LASTEST_TAG}

      - name: Show databend release version
        run: |
          echo "${{ steps.databend_version.outputs.VERSION }}"

      - uses: ./.github/actions/setup_k3d

      # TODO if version is not set ,use latest
      # from inputs: ${{ github.event.inputs.image_tags }}
      # from latest: {{ steps.databend_version.outputs.VERSION }}
      - name: Install databend-query and databend-meta by helm
        run: |
          helm repo add databend https://charts.databend.rs
          helm repo update
          helm upgrade --install databend-meta databend/databend-meta --namespace databend --create-namespace --set image.tag=${{ steps.databend_version.outputs.VERSION }}
          helm upgrade --install databend-query databend/databend-query --namespace databend --create-namespace --set image.tag=${{ steps.databend_version.outputs.VERSION }}

      - name: Wait for databend ready
        run: |
          sleep 10
          kubectl wait -n databend pod --for=condition=Ready --all --timeout=300s

      - if: ${{ failure() }}
        run: |
          kubectl describe pod `kubectl get pods -n databend |awk '{print $1}'` -n databend

      - name: Show all pods
        shell: bash
        run: |
          kubectl get pods -A

      - name: Export port locally
        run: |
          nohup kubectl port-forward -n databend svc/databend-query 3307:3307 2>&1 &
          nohup kubectl port-forward -n databend svc/databend-query 8001:8000 2>&1 &
          nohup kubectl port-forward -n databend svc/databend-query 9000:9000 2>&1 &

      # docker runtime
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run logic test by docker image
        run: |
          docker run --rm --name test --network host --env SKIP_TEST_FILES=06_0007_show_roles ${{github.event.inputs.logic_test_images}}
