name: databend logic test install by binary

on: 
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      image_tags:
        description: "tags of databend image"
        required: false
        default: v0.7.80-nightly

jobs:
  run-logic-test:
    name: Run logic test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # usage: steps.databend_version.ouputs.VERSION
      - name: Get Databend version
        id: databend_version
        run: |
          LASTEST_TAG=$(curl -s GET https://api.github.com/repos/datafuselabs/databend/tags\?per_page\=1 | jq -r '.[].name')
          echo ::set-output name=VERSION::${LASTEST_TAG}

      - name: Show databend release version
        run: |
          echo "${{ steps.databend_version.outputs.VERSION }}"

      - name: Install and run databend by binary
        run: |
          curl -LJO https://github.com/datafuselabs/databend/releases/download/${{ steps.databend_version.outputs.VERSION }}/databend-${{ steps.databend_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          tar zxvf databend-${{ steps.databend_version.outputs.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          ./scripts/start.sh

      #curl -LJO https://github.com/datafuselabs/databend/releases/download/v0.7.124-nightly/databend-v0.7.124-nightly-x86_64-unknown-linux-gnu.tar.gz
      #tar zxvf databend-v0.7.124-nightly-x86_64-unknown-linux-gnu.tar.gz
      #./scripts/start.sh

      # docker runtime
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run logic test by docker image latest
        run: |
          docker run --rm --name test --network host --env SKIP_TEST_FILES=06_0007_show_roles public.ecr.aws/i7g1w5q7/sqllogictest:latest

      - if: ${{ failure() }}
        name: Run logic test given version
        run: |
          docker run --rm --name test --network host --env SKIP_TEST_FILES=06_0007_show_roles public.ecr.aws/i7g1w5q7/sqllogictest:${{github.event.inputs.image_tags}}
