name: k3d

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - '.github/workflows/k3d.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - '.github/workflows/k3d.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_k3d

