name: python

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: System information
        shell: bash
        run: |
          df -h && lscpu && free -g

      - uses: ./.github/actions/setup_python

      - name: Install python dependences
        shell: bash
        run: |
          pip3 install --user six PyHamcrest requests environs fire

      - name: Install test
        shell: bash
        run: |
          pip3 install https://github.com/youngsofun/clickhouse-sqlalchemy/archive/a116e3162c699c12e63a689385b547f639c13018.zip
  
      - name: Python version
        shell: bash
        run: |
          python3 --version

      - name: Run python scripts
        run: |
          python3 ./python/demo.py
