name: python

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup_python

      - name: Install python dependences
        shell: bash
        run: |
          pip3 install --user fuzzingbook
  
      - name: Python version
        shell: bash
        run: |
          python3 --version

      - name: Run python scripts
        run: |
          python3 ./python/depend.py
