name: setup vm connect to teleport server

on: 
  workflow_dispatch:
    inputs:
      teleport-token:
        description: "teleport server token"
        required: true
        default: ""
      teleport-server:
        description: "teleport server address"
        required: true
        default: "teleport.xxx.xxx:443"
      user:
        description: "system admin user"
        required: true
        default: "ZeaLoVe"

jobs:
  vm-up:
    name: Start a ubuntu vm 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - run: |
         echo "TELEPORT_DOMAIN=${{ github.event.inputs.teleport-server }}" >> $GITHUB_ENV
         echo "TELEPORT_TOKEN=${{ github.event.inputs.teleport-token }}" >> $GITHUB_ENV
         echo "EC2_OWNER=${{ github.event.inputs.user }}" >> $GITHUB_ENV
         echo "EC2_USERS=${{ github.event.inputs.user }}" >> $GITHUB_ENV

      - run: |
         sudo chmod +x ./scripts/teleport/init.sh

      - run: |
         sudo ./scripts/teleport/init.sh

      - run: |
         sudo teleport start --roles=node --token=${{ github.event.inputs.teleport-token }} --auth-server=${{ github.event.inputs.teleport-server }}

      # - run: |
      #    sleep 500
